"""reconcile schema drift

Revision ID: 37f5b1de06fe
Revises: b3f23b1bd1f1
Create Date: 2026-08-18 13:50:35.293640

This migration reconciles db_models.py with the columns/constraints that
were already present in the live database (website, h1b_sponsorship,
created_at, updated_at, is_active, last_checked, department, and
date_posted's real timestamp type). Those already matched live, so no DDL
is needed for them here - only db_models.py changed. The only structural
change this migration executes is dropping the redundant `location`
column on job_postings, since job_locations is the canonical one-to-many
representation.

The buggy UniqueConstraint('company_id', ...) and the unique=True on
gh_job_id were declared in the ORM but were never actually enforced live
(they were never applied - see the "stamp head" migration), so there is
nothing to drop on the database side either; job_url's uniqueness is
already enforced live via job_postings_job_url_key, which the model now
names explicitly to match.

Data cleanup (steps 7-8 of the reconciliation) is included in this same
upgrade(), in a clearly separated block below the schema change, using
raw SQL via op.execute(). It is a one-time, hand-written data migration,
not autogenerated:
  7. Consolidate the two job_sources rows ("Greenhouse" and
     "greenhouse_api") into one canonical "Greenhouse" row.
  8. Delete the 53 job_postings rows with gh_job_id IS NULL (leftover
     manual test inserts), cascading to their job_locations/job_skills/
     job_metadata children first.

The data cleanup is not reversible (consolidated/deleted rows are gone),
so downgrade() only reverses the schema change and raises for the data
half - see downgrade() below.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f5b1de06fe'
down_revision: Union[str, Sequence[str], None] = 'b3f23b1bd1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Schema change -----------------------------------------------
    # job_locations is the canonical one-to-many representation; the
    # flat column on job_postings is redundant. Guarded because this
    # migration also needs to run cleanly against a fresh database that
    # never had the drifted `location` column in the first place.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('job_postings')]
    if 'location' in columns:
        op.drop_column('job_postings', 'location')

    # --- Data cleanup (steps 7-8) --------------------------------------
    # 7. Consolidate "greenhouse_api" into the canonical "Greenhouse" row.
    op.execute(sa.text("""
        UPDATE job_postings
        SET source_id = (SELECT id FROM job_sources WHERE name = 'Greenhouse')
        WHERE source_id = (SELECT id FROM job_sources WHERE name = 'greenhouse_api')
    """))
    op.execute(sa.text("DELETE FROM job_sources WHERE name = 'greenhouse_api'"))

    # 8. Delete leftover manual test rows (gh_job_id IS NULL), cleaning
    # up their child rows first to avoid orphaning them.
    op.execute(sa.text("""
        DELETE FROM job_locations
        WHERE job_id IN (SELECT id FROM job_postings WHERE gh_job_id IS NULL)
    """))
    op.execute(sa.text("""
        DELETE FROM job_skills
        WHERE job_id IN (SELECT id FROM job_postings WHERE gh_job_id IS NULL)
    """))
    op.execute(sa.text("""
        DELETE FROM job_metadata
        WHERE job_id IN (SELECT id FROM job_postings WHERE gh_job_id IS NULL)
    """))
    op.execute(sa.text("DELETE FROM job_postings WHERE gh_job_id IS NULL"))


def downgrade() -> None:
    # The data cleanup above (source consolidation, deleted test rows) is
    # destructive and cannot be reconstructed - there is no record of
    # which source_id each reassigned row used to have, or what the
    # deleted rows contained. Only the schema change is reversible.
    op.add_column(
        'job_postings',
        sa.Column('location', sa.String(length=255), nullable=True),
    )
    raise NotImplementedError(
        "The data cleanup in this migration (job_sources consolidation, "
        "deletion of gh_job_id IS NULL rows) is irreversible; downgrade() "
        "only restored the job_postings.location column."
    )
