"""add missing model columns not created by earlier migrations

Revision ID: 7c464378b3de
Revises: 37f5b1de06fe
Create Date: 2026-08-19 23:53:49.875913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c464378b3de'
down_revision: Union[str, Sequence[str], None] = '37f5b1de06fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('h1b_sponsorship', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('job_postings', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('job_postings', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('job_postings', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.alter_column('job_postings', 'date_posted',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='date_posted::timestamp without time zone')
    op.drop_constraint(op.f('_job_company_uc'), 'job_postings', type_='unique')
    op.drop_constraint(op.f('job_postings_gh_job_id_key'), 'job_postings', type_='unique')
    op.create_unique_constraint('job_postings_job_url_key', 'job_postings', ['job_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_postings_job_url_key', 'job_postings', type_='unique')
    op.create_unique_constraint(op.f('job_postings_gh_job_id_key'), 'job_postings', ['gh_job_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('_job_company_uc'), 'job_postings', ['company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_postings', 'date_posted',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('job_postings', 'last_checked')
    op.drop_column('job_postings', 'is_active')
    op.drop_column('job_postings', 'department')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'h1b_sponsorship')
    op.drop_column('companies', 'website')
    # ### end Alembic commands ###
