"""add lca_disclosures table

Revision ID: e4c81707e5e3
Revises: 7c464378b3de
Create Date: 2026-08-20 15:38:40.857433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c81707e5e3'
down_revision: Union[str, Sequence[str], None] = '7c464378b3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lca_disclosures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('employer_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('trade_name_dba', sa.String(length=255), nullable=True),
    sa.Column('case_status', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('soc_code', sa.String(length=20), nullable=True),
    sa.Column('soc_title', sa.String(length=255), nullable=True),
    sa.Column('worksite_city', sa.String(length=255), nullable=True),
    sa.Column('worksite_state', sa.String(length=10), nullable=True),
    sa.Column('worksite_postal_code', sa.String(length=20), nullable=True),
    sa.Column('wage_rate_of_pay_from', sa.Numeric(), nullable=True),
    sa.Column('wage_rate_of_pay_to', sa.Numeric(), nullable=True),
    sa.Column('wage_unit_of_pay', sa.String(length=20), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index(op.f('ix_lca_disclosures_employer_name'), 'lca_disclosures', ['employer_name'], unique=False)
    op.create_index(op.f('ix_lca_disclosures_employer_name_normalized'), 'lca_disclosures', ['employer_name_normalized'], unique=False)
    op.create_index(op.f('ix_lca_disclosures_fiscal_year'), 'lca_disclosures', ['fiscal_year'], unique=False)
    op.create_index('ix_lca_disclosures_fiscal_year_quarter', 'lca_disclosures', ['fiscal_year', 'quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lca_disclosures_fiscal_year_quarter', table_name='lca_disclosures')
    op.drop_index(op.f('ix_lca_disclosures_fiscal_year'), table_name='lca_disclosures')
    op.drop_index(op.f('ix_lca_disclosures_employer_name_normalized'), table_name='lca_disclosures')
    op.drop_index(op.f('ix_lca_disclosures_employer_name'), table_name='lca_disclosures')
    op.drop_table('lca_disclosures')
    # ### end Alembic commands ###
